CREATE TABLE locations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    address    VARCHAR(200),
    city       VARCHAR(100),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_locations_name UNIQUE (name)
);

CREATE TABLE zones (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    floor       INTEGER,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_zones_location FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE,
    CONSTRAINT uq_zones_location_name UNIQUE (location_id, name)
);
