CREATE TABLE networks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_id           BIGINT       NOT NULL,
    ssid              VARCHAR(64)  NOT NULL,
    bssid             VARCHAR(17)  NOT NULL,
    frequency_band    VARCHAR(10)  NOT NULL,
    channel           INTEGER      NOT NULL,
    security_type     VARCHAR(20)  NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
    data_source_type  VARCHAR(30)  NOT NULL DEFAULT 'SIMULATION',
    last_collected_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_networks_zone FOREIGN KEY (zone_id) REFERENCES zones (id) ON DELETE RESTRICT,
    CONSTRAINT uq_networks_bssid UNIQUE (bssid),
    CONSTRAINT ck_networks_bssid_format CHECK (bssid ~ '^([0-9A-F]{2}:){5}[0-9A-F]{2}$'),
    CONSTRAINT ck_networks_band CHECK (frequency_band IN ('2.4GHz', '5GHz', '6GHz')),
    CONSTRAINT ck_networks_channel CHECK (channel BETWEEN 1 AND 233),
    CONSTRAINT ck_networks_security CHECK (security_type IN ('OPEN', 'WPA2', 'WPA3', 'WPA2_ENTERPRISE')),
    CONSTRAINT ck_networks_status CHECK (status IN ('NORMAL', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_networks_data_source CHECK (
        data_source_type IN ('SIMULATION', 'ROUTER_API', 'SNMP', 'SYSTEM', 'TRAFFIC_CAPTURE'))
);
