CREATE TABLE devices (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id        BIGINT      NOT NULL,
    hostname          VARCHAR(100),
    ip_address        VARCHAR(45) NOT NULL,
    mac_address       VARCHAR(17) NOT NULL,
    device_type       VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
    connection_status VARCHAR(20) NOT NULL DEFAULT 'CONNECTED',
    signal_strength   INTEGER,
    last_seen_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_devices_network FOREIGN KEY (network_id) REFERENCES networks (id) ON DELETE CASCADE,
    CONSTRAINT uq_devices_mac UNIQUE (mac_address),
    CONSTRAINT ck_devices_mac_format CHECK (mac_address ~ '^([0-9A-F]{2}:){5}[0-9A-F]{2}$'),
    CONSTRAINT ck_devices_type CHECK (device_type IN ('LAPTOP', 'PHONE', 'TABLET', 'IOT', 'ACCESS_POINT', 'UNKNOWN')),
    CONSTRAINT ck_devices_status CHECK (connection_status IN ('CONNECTED', 'IDLE', 'DISCONNECTED')),
    CONSTRAINT ck_devices_signal CHECK (signal_strength BETWEEN -100 AND 0)
);
