-- Nullable metrics: some data sources cannot provide every value.
CREATE TABLE measurements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id          BIGINT           NOT NULL,
    latency_ms          DOUBLE PRECISION NOT NULL,
    jitter_ms           DOUBLE PRECISION NOT NULL,
    packet_loss_pct     DOUBLE PRECISION NOT NULL,
    bandwidth_mbps      DOUBLE PRECISION,
    signal_strength_dbm INTEGER,
    connected_devices   INTEGER,
    source              VARCHAR(30)      NOT NULL,
    measured_at         TIMESTAMPTZ      NOT NULL,
    created_at          TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_measurements_network FOREIGN KEY (network_id) REFERENCES networks (id) ON DELETE CASCADE,
    CONSTRAINT ck_measurements_latency CHECK (latency_ms >= 0),
    CONSTRAINT ck_measurements_jitter CHECK (jitter_ms >= 0),
    CONSTRAINT ck_measurements_packet_loss CHECK (packet_loss_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_measurements_bandwidth CHECK (bandwidth_mbps >= 0),
    CONSTRAINT ck_measurements_signal CHECK (signal_strength_dbm BETWEEN -100 AND 0),
    CONSTRAINT ck_measurements_devices CHECK (connected_devices >= 0)
);
