CREATE TABLE traffic_observations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id        BIGINT           NOT NULL,
    traffic_volume_mb DOUBLE PRECISION NOT NULL,
    packet_count      BIGINT           NOT NULL,
    observed_at       TIMESTAMPTZ      NOT NULL,
    created_at        TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_traffic_observations_network FOREIGN KEY (network_id) REFERENCES networks (id) ON DELETE CASCADE,
    CONSTRAINT ck_traffic_observations_volume CHECK (traffic_volume_mb >= 0),
    CONSTRAINT ck_traffic_observations_packets CHECK (packet_count >= 0)
);

CREATE TABLE traffic_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id        BIGINT      NOT NULL,
    protocol         VARCHAR(20) NOT NULL,
    destination_port INTEGER,
    bytes_sent       BIGINT      NOT NULL DEFAULT 0,
    bytes_received   BIGINT      NOT NULL DEFAULT 0,
    started_at       TIMESTAMPTZ NOT NULL,
    ended_at         TIMESTAMPTZ,
    CONSTRAINT fk_traffic_sessions_device FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE CASCADE,
    CONSTRAINT ck_traffic_sessions_port CHECK (destination_port BETWEEN 0 AND 65535),
    CONSTRAINT ck_traffic_sessions_bytes CHECK (bytes_sent >= 0 AND bytes_received >= 0),
    CONSTRAINT ck_traffic_sessions_period CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE protocol_statistics (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id   BIGINT      NOT NULL,
    protocol     VARCHAR(20) NOT NULL,
    packet_count BIGINT      NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end   TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_protocol_statistics_network FOREIGN KEY (network_id) REFERENCES networks (id) ON DELETE CASCADE,
    CONSTRAINT uq_protocol_statistics_period UNIQUE (network_id, protocol, period_start),
    CONSTRAINT ck_protocol_statistics_packets CHECK (packet_count >= 0),
    CONSTRAINT ck_protocol_statistics_period CHECK (period_end >= period_start)
);
