CREATE TABLE analysis_results (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id        BIGINT           NOT NULL,
    requested_by      BIGINT,
    analysis_type     VARCHAR(30)      NOT NULL,
    detected_status   VARCHAR(20)      NOT NULL,
    score             DOUBLE PRECISION NOT NULL,
    summary           VARCHAR(500)     NOT NULL,
    measurement_count INTEGER          NOT NULL,
    created_at        TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_analysis_results_network FOREIGN KEY (network_id) REFERENCES networks (id) ON DELETE CASCADE,
    CONSTRAINT fk_analysis_results_user FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_analysis_results_type CHECK (analysis_type IN ('THRESHOLD', 'STATISTICAL', 'ANOMALY_DETECTION')),
    CONSTRAINT ck_analysis_results_status CHECK (detected_status IN ('NORMAL', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_analysis_results_score CHECK (score BETWEEN 0 AND 1),
    CONSTRAINT ck_analysis_results_count CHECK (measurement_count > 0)
);

CREATE TABLE ai_predictions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_result_id BIGINT           NOT NULL,
    network_id         BIGINT           NOT NULL,
    anomaly_detected   BOOLEAN          NOT NULL,
    anomaly_score      DOUBLE PRECISION NOT NULL,
    severity           VARCHAR(10)      NOT NULL,
    message            VARCHAR(300)     NOT NULL,
    recommendation     VARCHAR(500),
    model_version      VARCHAR(50)      NOT NULL,
    simulated_data     BOOLEAN          NOT NULL,
    created_at         TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ai_predictions_analysis FOREIGN KEY (analysis_result_id) REFERENCES analysis_results (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_predictions_network FOREIGN KEY (network_id) REFERENCES networks (id) ON DELETE CASCADE,
    CONSTRAINT uq_ai_predictions_analysis UNIQUE (analysis_result_id),
    CONSTRAINT ck_ai_predictions_score CHECK (anomaly_score BETWEEN 0 AND 1),
    CONSTRAINT ck_ai_predictions_severity CHECK (severity IN ('NONE', 'LOW', 'MEDIUM', 'HIGH'))
);
