CREATE TABLE alerts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id         BIGINT       NOT NULL,
    analysis_result_id BIGINT,
    severity           VARCHAR(20)  NOT NULL,
    message            VARCHAR(300) NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    resolved_at        TIMESTAMPTZ,
    CONSTRAINT fk_alerts_network FOREIGN KEY (network_id) REFERENCES networks (id) ON DELETE CASCADE,
    CONSTRAINT fk_alerts_analysis FOREIGN KEY (analysis_result_id) REFERENCES analysis_results (id) ON DELETE SET NULL,
    CONSTRAINT ck_alerts_severity CHECK (severity IN ('INFO', 'WARNING', 'CRITICAL')),
    CONSTRAINT ck_alerts_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED')),
    CONSTRAINT ck_alerts_resolution CHECK (
        (status = 'RESOLVED' AND resolved_at IS NOT NULL) OR (status <> 'RESOLVED' AND resolved_at IS NULL))
);
